### ISSUE TITLE
Deploy ScrolTable to NPM

### ISSUE THREAD

**Issue by ZeroGazer** [cytim/jquery-scroltable#6]

**Comment by cytim** [comment]
Completed by 87f6955.
Since ESLint depends on a node module, I configured to publish the plugin to NPM as well.
https://www.npmjs.com/package/jquery-scroltable

Follow up:
- Follow [this](http://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm) to better adapt the NPM environment.
- Include @chpoon92 to the package as a contributor. (Please create an account on NPM.)
